# Base image
FROM node:20-bullseye

WORKDIR /app

COPY package*.json ./
COPY package-lock.json ./

COPY packages ./packages
COPY api-gateway ./api-gateway

RUN npm install --workspaces --legacy-peer-deps

# Build the workspace you care about
RUN npm run build --workspace=api-gateway

# Expose port if needed
EXPOSE 3000

# Run the worker using npm workspace
CMD ["npm", "start", "--workspace=api-gateway"]