services:
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile.dev
    container_name: api-gateway
    ports:
      - "8001:3000"
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./packages/domain:/app/packages/domain
    networks:
      - veren
    depends_on:
      - internal-redis

  routing-service:
    build:
      context: .
      dockerfile: ./routing-service/Dockerfile.dev
    container_name: routing-service
    volumes:
      - ./routing-service:/src
    ports:
      - "8004:3000"
    env_file:
      - ./routing-service/.env
    networks:
      - veren 
    depends_on:
      - api-gateway

  orchestrate-service:
    build:
      context: .
      dockerfile: ./orchestrate-service/Dockerfile.dev
    container_name: orchestrate-service
    volumes:
      - ./orchestrate-service:/src
    ports:
      - "8005:3000"
    env_file:
      - ./orchestrate-service/.env
    networks:
      - veren  
    depends_on:
      - api-gateway
  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile.dev
    container_name: notification-service
    volumes:
      - ./notification-service:/src
    ports:
      - "8007:3000"
    env_file:
      - ./notification-service/.env
    networks:
      - veren

  frontend-build-worker:
    build:
      context: .
      dockerfile: ./WORKERS/frontend-build-worker/Dockerfile
    privileged: true
    env_file:
      - ./WORKERS/frontend-build-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis  

  backend-build-worker:
    build:
      context: .
      dockerfile: ./WORKERS/backend-build-worker/Dockerfile
    privileged: true
    env_file:
      - ./WORKERS/backend-build-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis 
  backend-deploy-worker:
    build:
      context: .
      dockerfile: ./WORKERS/backend-deploy-worker/Dockerfile
    privileged: true
    env_file:
      - ./WORKERS/backend-deploy-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis
  log-worker:
    build:
      context: .
      dockerfile: ./WORKERS/log-worker/Dockerfile
    privileged: true
    env_file:
      - ./WORKERS/log-worker/.env
    networks:
      - veren
    depends_on:
      - internal-redis

  internal-redis:
    image: redis:7
    container_name: notification_internal_redis
    restart: always
    networks:
      - veren
    volumes:
    - redis-data:/data

volumes:
  redis-data:

networks:
  veren:
    external: false