export type DeploymentStatusI = "CREATED"
  | "INTERNAL_ERROR"
  | "FRONTEND_BUILD_QUEUED"
  | "FRONTEND_BUILD_FAILED"
  | "FRONTEND_BUILD_SUCCESS"
  | "BACKEND_BUILD_QUEUED"
  | "BACKEND_BUILDING"
  | "BACKEND_BUILD_FAILED"
  | "BACKEND_BUILD_SUCCESS"
  | "BACKEND_DEPLOY_QUEUED"
  | "BACKEND_DEPLOYING"
  | "BACKEND_DEPLOY_FAILED"
  | "BACKEND_DEPLOYED" 


export enum DeploymentStatus {
  CREATED = "CREATED",
  INTERNAL_ERROR = "INTERNAL_ERROR",

  FRONTEND_BUILD_QUEUED = "FRONTEND_BUILD_QUEUED",
  FRONTEND_BUILD_FAILED = "FRONTEND_BUILD_FAILED",
  FRONTEND_BUILD_SUCCESS = "FRONTEND_BUILD_SUCCESS",

  BACKEND_BUILD_QUEUED = "BACKEND_BUILD_QUEUED",
  BACKEND_BUILDING = "BACKEND_BUILDING",
  BACKEND_BUILD_FAILED = "BACKEND_BUILD_FAILED",
  BACKEND_BUILD_SUCCESS = "BACKEND_BUILD_SUCCESS",

  BACKEND_DEPLOY_QUEUED = "BACKEND_DEPLOY_QUEUED",
  BACKEND_DEPLOYING = "BACKEND_DEPLOYING",
  BACKEND_DEPLOY_FAILED = "BACKEND_DEPLOY_FAILED",
  BACKEND_DEPLOYED = "BACKEND_DEPLOYED"
}