FROM node:20-bullseye

WORKDIR /src

# Install deps (include devDependencies since we need nodemon + ts-node inside container)
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install

# Copy everything else
COPY . .

# Default port (will be overridden by docker-compose)
EXPOSE 3000

# Run dev server with nodemon + ts-node/esm
CMD ["npm", "run", "dev"]
