FROM ubuntu:focal

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt-get upgrade -y
RUN apt-get install -y nodejs

RUN apt-get install git -y

WORKDIR /home/app

COPY main.sh main.sh
COPY script.js script.js
COPY utils ./utils
COPY package*.json .
COPY kafka.pem kafka.pem
COPY publisher.js publisher.js

RUN npm install

RUN chmod +x script.js
RUN chmod +x main.sh

ENTRYPOINT [ "/home/app/main.sh" ]